include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/generated_*.dart"

linter:
  rules:
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_returning_null_for_void: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    prefer_const_constructors: true
