name: double_tap
description: "This proyect is a flutter app that uses the valorant api to get the valorant user information and show items in the store"

version: 2.0.0+4

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  webview_flutter: ^4.8.0
  jwt_decode: ^0.3.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  slide_countdown: ^1.6.1
  animate_do: ^3.3.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  uuid: ^4.4.2
  video_player: ^2.9.1
  shorebird_code_push: ^1.1.3
  restart_app: ^1.2.1
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.4.1
  simple_floating_bottom_nav_bar: ^0.0.3
  package_info_plus: ^8.0.0
  flutter_hooks: ^0.20.5
  flutter_gen_runner: ^5.6.0
  cookie_jar: ^4.0.8
  # flutter_background_service: ^5.0.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  freezed: ^2.5.2

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#001528"
  adaptive_icon_foreground: "assets/icon/icon.png"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#001528"
  image: assets/icon/icon.png
  color_dark: "#001528"

  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#001528"

flutter:
  uses-material-design: true

  assets:
    - assets/valorant/wallet/
    - assets/icon/
    - shorebird.yaml
