name: double_tap
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  webview_flutter: ^4.8.0
  jwt_decode: ^0.3.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  slide_countdown: ^1.6.1
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/valorant/wallet/