import 'package:flutter/material.dart';

class ThemeApp {
  static getTheme() => ThemeData(
        splashColor: Colors.transparent,
        highlightColor: Colors.transparent,
        hoverColor: Colors.transparent,
        scaffoldBackgroundColor: Colors.black,
        colorScheme: ColorScheme.fromSeed(
          brightness: Brightness.dark,
          seedColor: Colors.black,
          onPrimary: Colors.black,
          onSecondary: Colors.black,
          onTertiary: Colors.black,
          onError: Colors.black,
          onSurface: Colors.white,
          onSurfaceVariant: Colors.white,
          onInverseSurface: Colors.black,
          error: Colors.black,
          errorContainer: Colors.black,
          onErrorContainer: Colors.black,
          inversePrimary: Colors.black,
          onPrimaryContainer: Colors.black,
          primaryContainer: Colors.black,
          secondary: Colors.black,
          secondaryContainer: Colors.black,
          tertiary: Colors.black,
          tertiaryContainer: Colors.black,
          inverseSurface: Colors.black,
          onSecondaryContainer: Colors.black,
          onTertiaryContainer: Colors.black,
          outline: Colors.black,
          outlineVariant: Colors.black,
          primary: Colors.white,
          scrim: Colors.black,
          shadow: Colors.black,
          surface: Colors.black,
          surfaceTint: Colors.black,
        ),
        useMaterial3: true,
      );
}
